name: lmrepaircrmadmin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  dio: ^5.7.0
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  provider: ^6.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  multi_select_flutter: ^4.1.3
  geolocator: ^13.0.2
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env


  