// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8WOgJkMTO1vBVjhldNPCBelvpbcDR5Mk',
    appId: '1:631134926632:web:b81d5e9792f0c15b77c21d',
    messagingSenderId: '631134926632',
    projectId: 'limsoncrm',
    authDomain: 'limsoncrm.firebaseapp.com',
    storageBucket: 'limsoncrm.firebasestorage.app',
    measurementId: 'G-JDE303VBFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqAjTU-OweE2oMHBSzFuRlBW-LRzO081Q',
    appId: '1:631134926632:android:8f21930ab3b9aa1f77c21d',
    messagingSenderId: '631134926632',
    projectId: 'limsoncrm',
    storageBucket: 'limsoncrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByJGF11DIlE99hOFOpRc8urftOK07-Oio',
    appId: '1:631134926632:ios:8a0594389735754977c21d',
    messagingSenderId: '631134926632',
    projectId: 'limsoncrm',
    storageBucket: 'limsoncrm.firebasestorage.app',
    iosBundleId: 'com.example.lmrepaircrmadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByJGF11DIlE99hOFOpRc8urftOK07-Oio',
    appId: '1:631134926632:ios:8a0594389735754977c21d',
    messagingSenderId: '631134926632',
    projectId: 'limsoncrm',
    storageBucket: 'limsoncrm.firebasestorage.app',
    iosBundleId: 'com.example.lmrepaircrmadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8WOgJkMTO1vBVjhldNPCBelvpbcDR5Mk',
    appId: '1:631134926632:web:72524ab67bc944ea77c21d',
    messagingSenderId: '631134926632',
    projectId: 'limsoncrm',
    authDomain: 'limsoncrm.firebaseapp.com',
    storageBucket: 'limsoncrm.firebasestorage.app',
    measurementId: 'G-L551FYNRNF',
  );
}
